TARGET_LANGUAGES = {
    'Modern Standard Arabic': 'arb',
    'Bengali': 'ben',
    'Catalan': 'cat',
    'Czech': 'ces',
    'Mandarin Chinese': 'cmn',
    'Welsh': 'cym',
    'Danish': 'dan',
    'German': 'deu',
    'English': 'eng',
    'Estonian': 'est',
    'French': 'fra',
    'Hindi': 'hin',
    'Indonesian': 'ind',
    'Italian': 'ita',
    'Japanese': 'jpn',
    'Korean': 'kor',
    'Maltese': 'mlt',
    'Dutch': 'nld',
    'Polish': 'pol',
    'Portuguese': 'por',
    'Romanian': 'ron',
    'Russian': 'rus',
    'Slovak': 'slk',
    'Spanish': 'spa',
    'Swedish': 'swe',
    'Swahili': 'swh',
    'Thai': 'tha',
    'Turkish': 'tur',
    'Ukrainian': 'ukr',
    'Urdu': 'urd',
    'Vietnamese': 'vie'
}
